# Generated by Django 4.0.5 on 2022-07-19 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_posts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 21, 28, 23, 67884)),
        ),
    ]
